# # me1 = MediaEntry.create(title: "The Way of Kings", description: "First book in the Stormlight Archives", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/81pJXhRLdoL.jpg", creator: "Brandon Sanderson")

# # me2 = MediaEntry.create(title: "Words of Radiance", description: "Second book in the Stormlight Archives", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/91tECQfrZTL.jpg", creator: "Brandon Sanderson")

# # me3 = MediaEntry.create(title: "Interstellar", description: "In Earth's future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand (Michael Caine), a brilliant NASA physicist, is working on plans to save mankind by transporting Earth's population to a new home via a wormhole. But first, Brand must send former NASA pilot Cooper (Matthew McConaughey) and a team of researchers through the wormhole and across the galaxy to find out which of three planets could be mankind's new home.", media_type: "Movie", image_url: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg", creator: "Christopher Nolan")

# # user1 = User.create(full_name: "Alejandro Juarez", email: "alj@example.com", password: "password", password_confirmation: "password", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg")

# # user2 = User.create(full_name: "Heimer Dugan", email: "heimer@example.com", password: "password", password_confirmation: "password", image_url: "https://cdn.vectorstock.com/i/1000v/92/16/default-profile-picture-avatar-user-icon-vector-46389216.jpg")

# # me4 = MediaEntry.create(title: "Oathbringer", description: "Third book in the Stormlight Archives", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/91x4fchgt2L.jpg", creator: "Brandon Sanderson")

# # me5 = MediaEntry.create(title: "Edgedancer", description: "First Novella in the Stormlight Archives, book 2.5", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/81SuJQI8uNL.jpg", creator: "Brandon Sanderson")

# # me6 = MediaEntry.create(title: "Dawnshard", description: "Second Novella in the Stormlight Archives, book 3.5", media_type: "Book", image_url: "https://mpd-biblio-covers.imgix.net/9781250850553.jpg", creator: "Brandon Sanderson")

# # me7 = MediaEntry.create(title: "Rhythm of War", description: "Fourth book in the Stormlight Archives", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/81ZR25hH7eL.jpg", creator: "Brandon Sanderson")

# # me8 = MediaEntry.create(title: "Wind and Truth", description: "Fifth book in the Stormlight Archives", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/81oQNU2eoPL.jpg", creator: "Brandon Sanderson")

# # me9 = MediaEntry.create(title: "The Final Empire", description: "First book in the Mistborn series", media_type: "Book", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrxLr2D2kB07AW3YZaDaqqne_2wMUUWCf24A&s", creator: "Brandon Sanderson")

# # me10 = MediaEntry.create(title: "The Well of Ascension", description: "Second book in the Mistborn series", media_type: "Book", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc8EgDyegJx_Kr5z5_dpufs8IR0W7FSeomjA&s", creator: "Brandon Sanderson")

# # me11 = MediaEntry.create(title: "The Last of Us", description: "In a ravaged world, Joel and Ellie must navigate a post-apocalyptic America filled with danger and despair. Their bond is tested as they face the harsh realities of survival.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_.jpg", creator: "Craig Mazin")

# # me12 = MediaEntry.create(title: "The Witcher", description: "Geralt of Rivia, a mutated monster hunter, navigates a world where humans can be more monstrous than the beasts he hunts. His destiny intertwines with powerful sorceresses and a young princess.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BMTQ5MDU5MTktMDZkMy00NDU1LWIxM2UtODg5OGFiNmRhNDBjXkEyXkFqcGc@._V1_.jpg", creator: "Lauren Schmidt Hissrich")

# # me13 = MediaEntry.create(title: "Zombieland", description: "In a post-apocalyptic world overrun by zombies, a group of survivors navigates the chaos with humor and ingenuity. They form unlikely alliances and face absurd challenges in their quest for safety.", media_type: "Movie", image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Zombieland-poster.jpg/250px-Zombieland-poster.jpg", creator: "Ruben Fleischer")

# me14 = MediaEntry.create(title: "The Martian", description: "An astronaut is stranded on Mars and must use his ingenuity to survive while awaiting rescue. He faces challenges of isolation, resourcefulness, and the will to live.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/I/71r+KR193uL._AC_UF894,1000_QL80_.jpg", creator: "Ridley Scott")

# me15 = MediaEntry.create(title: "Warfare", description: "A surveillance mission goes wrong for a platoon of American Navy SEALs in insurgent territory in Iraq.", media_type: "Movie", image_url: "https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w:auto/h:auto/q:75/https://bleedingcool.com/wp-content/uploads/2025/03/warfare_ver3-1.jpg", creator: "Alex Garland")

# me16 = MediaEntry.create(title: "Man of Steel", description: "Clark Kent, one of the last of his kind, is forced to reveal his identity when Earth is invaded by a powerful alien force. He must embrace his destiny as Superman to protect humanity.", media_type: "Movie", image_url: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9259673_p_v10_an.jpg", creator: "Zack Snyder")

# me17 = MediaEntry.create(title: "Talk to Me", description: "A group of friends discovers a way to conjure spirits using an embalmed hand. They become addicted to the thrill, but when one of them goes too far, they unleash terrifying supernatural forces.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/M/MV5BY2I2NzJmY2YtYTM3Ni00ZGJhLThkZTItODFhMzhlZjZkMDQ5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", creator: "Danny Philippou")

# me18 = MediaEntry.create(title: "28 Years Later", description: "It's been almost three decades since the rage virus escaped from a biological weapons laboratory. Still living in a ruthlessly enforced quarantine, some have found ways to exist amid the infected. One such group of survivors lives on a small island connected to the mainland by a single, heavily defended causeway. When one of them decides to venture into the dark heart of the mainland, he soon discovers a mutation that has spread to not only the infected, but other survivors as well.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/M/MV5BNjgwYTI0YjctMWYzNS00MmI1LWI5YTctNmE1YjBkNDFlNWMxXkEyXkFqcGc@._V1_.jpg", creator: "Danny Boyle")

# me19 = MediaEntry.create(title: "A Minecraft Movie", description: "A mysterious portal pulls four misfits into the Overworld, a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master the terrain while embarking on a magical quest with an unexpected crafter named Steve.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/M/MV5BYzFjMzNjOTktNDBlNy00YWZhLWExYTctZDcxNDA4OWVhOTJjXkEyXkFqcGc@._V1_.jpg", creator: "Jared Hess")

# me20 = MediaEntry.create(title: "Saving Private Ryan", description: "During the invasion of Normandy, Captain Miller and his squad are tasked with finding and bringing home Private Ryan, whose brothers have been killed in action. The mission is fraught with danger and moral dilemmas.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", creator: "Steven Spielberg")

# me21 = MediaEntry.create(title: "Oppenheimer", description: "A dramatization of the life story of J. Robert Oppenheimer, the physicist who had a large hand in the development of the atomic bombs that brought an end to World War II.", media_type: "Movie", image_url: "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", creator: "Christopher Nolan")

# me22 = MediaEntry.create(title: "Red Rising", description: "In a future society divided by color-coded classes, Darrow, a lowly Red, infiltrates the elite Golds to ignite a revolution. He faces betrayal, love, and the struggle for freedom in a brutal world.", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/81wGzzxqHSL._AC_UF1000,1000_QL80_.jpg", creator: "Pierce Brown")

# me23 = MediaEntry.create(title: "Golden Son", description: "Darrow, now a Gold, navigates the treacherous world of the elite while seeking revenge against those who wronged him. As he rises in power, he must confront the moral complexities of leadership and loyalty.", media_type: "Book", image_url: "https://m.media-amazon.com/images/I/61HFDxBnhxL._AC_UF1000,1000_QL80_.jpg", creator: "Pierce Brown")

# me24 = MediaEntry.create(title: "The 100", description: "When nuclear Armageddon destroys civilization on Earth, the only survivors are those on the 12 international space stations in orbit at the time. Three generations later, the 4,000 survivors living on a space ark of linked stations see their resources dwindle and face draconian measures established to ensure humanity's future. Desperately looking for a solution, the ark's leaders send 100 juvenile prisoners back to the planet to test its habitability. Having always lived in space, the exiles find the planet fascinating and terrifying, but with the fate of the human race in their hands, they must forge a path into the unknown.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BNDdmZGYwOWEtN2FkZC00Y2ExLWJkY2UtNzFlODVlNzc3MGIzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", creator: "Jason Rothenberg")

# me25 = MediaEntry.create(title: "Doctor Who", description: "A time-traveling alien known as the Doctor travels through time and space in the TARDIS, a time machine that looks like a British police box. With various companions, the Doctor faces foes and saves civilizations while exploring the universe.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/I/71XPVYAU+cL._AC_UF894,1000_QL80_.jpg", creator: "Sydney Newman, Donald Wilson, C. E. Webber")

# me26 = MediaEntry.create(title: "Supernatural", description: "Two brothers, Sam and Dean Winchester, hunt demons, ghosts, monsters, and other supernatural beings. They travel across the country in their iconic Chevy Impala, facing personal demons and family secrets along the way.", media_type: "TV Show", image_url: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p185113_b_v13_bg.jpg", creator: "Eric Kripke")

# me27 = MediaEntry.create(title: "Black Mirror", description: "A collection of stand-alone dramas that explore a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide. Each episode presents a different story, often with a dystopian or satirical twist.", media_type: "TV Show", image_url: "https://static.wikia.nocookie.net/best-tv-shows/images/6/66/Black_Mirror.jpg/revision/latest?cb=20220528102419", creator: "Charlie Brooker")

# me28 = MediaEntry.create(title: "Love, Death, and Robots", description: "An anthology series that blends animated short stories across various genres, including science fiction, fantasy, horror, and comedy. Each episode features unique animation styles and explores themes of love, death, and technology.", media_type: "TV Show", image_url: "https://static.wikia.nocookie.net/lovedeathrobots/images/0/08/Love_Death_and_Robots_Vol_3_Promotional_Poster.jpg/revision/latest?cb=20220519072614", creator: "Tim Miller")

# me29 = MediaEntry.create(title: "Jujutsu Kaisen", description: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BNmI1MmYxNWQtY2E5NC00ZTlmLWIzZGEtNzM1YmE3NDA5NzhjXkEyXkFqcGc@._V1_.jpg", creator: "Gege Akutami")

# me30 = MediaEntry.create(title: "Solo Leveling", description: "In a world where hunters battle monsters, the weakest hunter, Sung Jin-Woo, discovers a hidden power that allows him to level up and become the strongest. He embarks on a journey to uncover the truth behind his abilities and the mysterious dungeons.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BYTIwYzk3YmQtZmMwNS00ZDAwLTk5Y2MtOTEwODFlZmExMzliXkEyXkFqcGc@._V1_.jpg", creator: "Chugong")

# me31 = MediaEntry.create(title: "Dexter", description: "Dexter Morgan is a Miami-based blood splatter expert who doesn't just solve murders; he commits them too. In fact, he's a serial killer -- but he only murders the guilty, so he feels justified with his lifestyle choices. His policewoman sister and his cop co-workers have no idea Dexter lives a double life; however, adoptive father Harry knows his secret, and does, in fact, help Dexter hone his 'skills.' It's a unique brand of justice for which charming Dexter feels a psychological hunger.", media_type: "TV Show", image_url: "https://m.media-amazon.com/images/M/MV5BMTQ3YmQ4YzMtOTkyZC00YmM5LThhZjEtM2E0MjFkNTc0OGJhXkEyXkFqcGc@._V1_QL75_UY281_CR14,0,190,281_.jpg", creator: "John Dahl")